# Generated by Django 6.0.1 on 2026-02-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='accoun_tier',
            new_name='account_tier',
        ),
    ]
