# Generated by Django 6.0.1 on 2026-02-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_accoun_tier_customuser_account_tier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='status_choice',
            new_name='status',
        ),
    ]
